<?php

namespace App\Support;

/**
 * Catalogue dynamique des modules GreenPOS Enterprise (Module Store).
 */
class ModuleCatalog
{
    /** Modules toujours visibles (shell minimal). */
    public const ALWAYS_ON = ['dashboard', 'modules'];

    /** Filtres du Module Store (ordre d’affichage). */
    public const STORE_FILTERS = [
        'Tous',
        'Vente',
        'Catalogue',
        'Stock',
        'Finance',
        'Gestion',
        'Administration',
        'Intelligence',
        'Intégrations',
        'Mobile',
    ];

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            'dashboard' => self::def([
                'name' => 'Dashboard',
                'description' => 'Tableau de bord opérationnel et KPIs temps réel.',
                'long_description' => 'Centralisez l’activité de votre entreprise : ventes du jour, alertes stock, encours clients et indicateurs clés. Le Dashboard GreenPOS s’adapte aux modules installés pour n’afficher que ce qui compte.',
                'version' => '2.1.0',
                'category' => 'Gestion',
                'icon' => 'dashboard',
                'color' => '#0d9488',
                'permission' => null,
                'route' => 'home',
                'route_is' => 'home',
                'nav_group' => 'Pilotage',
                'nav_label' => 'Tableau de bord',
                'rating' => 4.9,
                'installs' => 18420,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['updated'],
                'features' => [
                    'KPIs ventes, stock et finance',
                    'Widgets adaptés aux modules actifs',
                    'Alertes prioritaires en un coup d’œil',
                    'Raccourcis vers les actions fréquentes',
                ],
                'changelog' => [
                    ['version' => '2.1.0', 'date' => '2026-07-28', 'notes' => 'Nouveaux widgets et mode sombre raffiné.'],
                    ['version' => '2.0.0', 'date' => '2026-05-10', 'notes' => 'Refonte visuelle et performances.'],
                ],
                'related' => ['reports', 'ai', 'notifications'],
            ]),
            'products' => self::def([
                'name' => 'Produits',
                'description' => 'Catalogue produits, variantes, codes-barres et prix.',
                'long_description' => 'Pilotez tout votre catalogue : fiches produits, variantes, images, tarifs multi-boutiques et historique des modifications. Conçu pour les enseignes retail et multi-magasins.',
                'version' => '2.3.2',
                'category' => 'Catalogue',
                'icon' => 'products',
                'color' => '#0891b2',
                'permission' => 'products.view',
                'route' => 'products.index',
                'route_is' => 'products.*',
                'nav_group' => 'Catalogue',
                'nav_label' => 'Produits',
                'rating' => 4.8,
                'installs' => 16210,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => [],
                'features' => [
                    'Fiches produits & variantes',
                    'Gestion des prix et TVA',
                    'Images et documents associés',
                    'Historique des changements',
                ],
                'changelog' => [
                    ['version' => '2.3.2', 'date' => '2026-07-15', 'notes' => 'Amélioration import masse et variantes.'],
                ],
                'related' => ['categories', 'brands', 'stock'],
            ]),
            'categories' => self::def([
                'name' => 'Catégories',
                'description' => 'Organisation arborescente du catalogue.',
                'long_description' => 'Structurez votre offre en catégories et sous-catégories claires pour accélérer la recherche en caisse et sur le web.',
                'version' => '1.8.0',
                'category' => 'Catalogue',
                'icon' => 'categories',
                'color' => '#06b6d4',
                'permission' => 'products.view',
                'route' => 'products.index',
                'route_is' => 'products.*',
                'nav_group' => null,
                'rating' => 4.6,
                'installs' => 14102,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Arborescence illimitée', 'Ordre d’affichage', 'Visibilité par boutique'],
                'related' => ['products', 'brands'],
            ]),
            'brands' => self::def([
                'name' => 'Marques',
                'description' => 'Gestion des marques et gammes produits.',
                'long_description' => 'Associez chaque produit à sa marque pour filtrer, analyser et présenter votre catalogue avec professionnalisme.',
                'version' => '1.5.1',
                'category' => 'Catalogue',
                'icon' => 'brands',
                'color' => '#22d3ee',
                'permission' => 'products.view',
                'route' => 'products.index',
                'route_is' => 'products.*',
                'nav_group' => null,
                'rating' => 4.5,
                'installs' => 12880,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Fiches marques', 'Logo & description', 'Filtres catalogue'],
                'related' => ['products', 'categories'],
            ]),
            'stock' => self::def([
                'name' => 'Stock',
                'description' => 'Niveaux, mouvements et alertes de stock.',
                'long_description' => 'Suivez les stocks en temps réel multi-boutiques, déclenchez des alertes de rupture et analysez les mouvements entrées/sorties.',
                'version' => '2.2.0',
                'category' => 'Stock',
                'icon' => 'stock',
                'color' => '#059669',
                'permission' => 'stock.view',
                'route' => 'stock.dashboard',
                'route_is' => 'stock.*',
                'nav_group' => 'Catalogue',
                'nav_label' => 'Stock',
                'rating' => 4.8,
                'installs' => 15540,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['updated'],
                'features' => [
                    'Stock multi-boutiques',
                    'Alertes seuil minimum',
                    'Historique des mouvements',
                    'Valorisation du stock',
                ],
                'prerequisites' => ['products'],
                'related' => ['inventory', 'purchases', 'products'],
            ]),
            'inventory' => self::def([
                'name' => 'Inventaire',
                'description' => 'Sessions d’inventaire, comptages et écarts.',
                'long_description' => 'Organisez des inventaires partiels ou complets, saisissez les comptages et validez les écarts en toute traçabilité.',
                'version' => '1.9.0',
                'category' => 'Stock',
                'icon' => 'inventory',
                'color' => '#10b981',
                'permission' => 'stock.inventory',
                'route' => 'stock.inventories.index',
                'route_is' => 'stock.inventories.*',
                'nav_group' => null,
                'rating' => 4.7,
                'installs' => 9840,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Inventaires guidés', 'Écarts automatiques', 'Validation contrôlée'],
                'prerequisites' => ['stock'],
                'related' => ['stock', 'purchases'],
            ]),
            'purchases' => self::def([
                'name' => 'Achats',
                'description' => 'Commandes fournisseurs et réceptions.',
                'long_description' => 'De la demande d’achat à la réception : créez des commandes, suivez les livraisons et mettez à jour le stock automatiquement.',
                'version' => '2.0.4',
                'category' => 'Stock',
                'icon' => 'purchases',
                'color' => '#047857',
                'permission' => 'purchases.view',
                'route' => 'purchases.dashboard',
                'route_is' => 'purchases.*',
                'nav_group' => 'Catalogue',
                'nav_label' => 'Achats',
                'rating' => 4.7,
                'installs' => 11220,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Bons de commande', 'Réceptions partielles', 'Lien stock automatique'],
                'related' => ['suppliers', 'stock', 'inventory'],
            ]),
            'suppliers' => self::def([
                'name' => 'Fournisseurs',
                'description' => 'Fiches, documents et historique fournisseurs.',
                'long_description' => 'Centralisez vos partenaires achats : contacts, conditions, documents et historique de commandes.',
                'version' => '1.7.0',
                'category' => 'Stock',
                'icon' => 'suppliers',
                'color' => '#34d399',
                'permission' => 'suppliers.view',
                'route' => 'suppliers.dashboard',
                'route_is' => 'suppliers.*',
                'nav_group' => 'Catalogue',
                'nav_label' => 'Fournisseurs',
                'rating' => 4.6,
                'installs' => 10950,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Fiches complètes', 'Documents attachés', 'Historique d’achats'],
                'related' => ['purchases', 'stock'],
            ]),
            'customers' => self::def([
                'name' => 'Clients',
                'description' => 'Base clients, contacts et historique.',
                'long_description' => 'Construisez une base clients solide : fiches, contacts, documents et historique d’achats pour un service personnalisé.',
                'version' => '2.1.3',
                'category' => 'Vente',
                'icon' => 'customers',
                'color' => '#0284c7',
                'permission' => 'customers.view',
                'route' => 'customers.dashboard',
                'route_is' => 'customers.*',
                'nav_group' => 'Relation Client',
                'nav_label' => 'Clients',
                'rating' => 4.8,
                'installs' => 15890,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Fiches B2C / B2B', 'Contacts multiples', 'Historique commercial'],
                'related' => ['pos', 'sales', 'crm'],
            ]),
            'pos' => self::def([
                'name' => 'POS',
                'description' => 'Caisse tactile, sessions et tickets.',
                'long_description' => 'Une caisse moderne, rapide et fiable : sessions de caisse, scan codes-barres, remises, paiements multiples et tickets imprimables.',
                'version' => '3.0.1',
                'category' => 'Vente',
                'icon' => 'pos',
                'color' => '#65a30d',
                'permission' => 'pos.view',
                'route' => 'pos.dashboard',
                'route_is' => 'pos.*',
                'nav_group' => 'Ventes',
                'nav_label' => 'POS / Caisse',
                'rating' => 4.9,
                'installs' => 17100,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['updated'],
                'features' => [
                    'Interface caisse ultra-rapide',
                    'Sessions & clôtures',
                    'Paiements mixtes',
                    'Tickets et retours',
                ],
                'prerequisites' => ['products'],
                'related' => ['sales', 'payments', 'customers'],
            ]),
            'sales' => self::def([
                'name' => 'Ventes',
                'description' => 'Historique des ventes et retours comptoir.',
                'long_description' => 'Consultez, filtrez et analysez toutes vos ventes. Gérez les retours et conservez une traçabilité complète.',
                'version' => '2.0.0',
                'category' => 'Vente',
                'icon' => 'sales',
                'color' => '#84cc16',
                'permission' => 'sales.view',
                'route' => 'sales.dashboard',
                'route_is' => 'sales.*',
                'nav_group' => 'Ventes',
                'nav_label' => 'Ventes',
                'rating' => 4.7,
                'installs' => 14920,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Historique détaillé', 'Retours', 'Filtres avancés'],
                'related' => ['pos', 'invoices', 'reports'],
            ]),
            'quotes' => self::def([
                'name' => 'Devis',
                'description' => 'Devis commerciaux et conversion en vente.',
                'long_description' => 'Créez des devis professionnels, suivez leur statut et convertissez-les en factures ou ventes en un clic.',
                'version' => '1.6.2',
                'category' => 'Vente',
                'icon' => 'quotes',
                'color' => '#ca8a04',
                'permission' => 'quotes.view',
                'route' => 'quotes.dashboard',
                'route_is' => 'quotes.*',
                'nav_group' => 'Finance',
                'nav_label' => 'Devis',
                'rating' => 4.6,
                'installs' => 8760,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Modèles de devis', 'Conversion en facture', 'Suivi des statuts'],
                'related' => ['invoices', 'customers', 'sales'],
            ]),
            'invoices' => self::def([
                'name' => 'Facturation',
                'description' => 'Factures, PDF et suivi des paiements.',
                'long_description' => 'Émettez des factures conformes, générez des PDF soignés et suivez les encaissements jusqu’au solde.',
                'version' => '2.4.0',
                'category' => 'Vente',
                'icon' => 'invoices',
                'color' => '#d97706',
                'permission' => 'invoices.view',
                'route' => 'invoices.dashboard',
                'route_is' => 'invoices.*',
                'nav_group' => 'Finance',
                'nav_label' => 'Facturation',
                'rating' => 4.8,
                'installs' => 13450,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['updated'],
                'features' => ['Factures PDF', 'Numérotation', 'Suivi des soldes', 'Avoirs'],
                'related' => ['payments', 'quotes', 'customers'],
            ]),
            'payments' => self::def([
                'name' => 'Paiements',
                'description' => 'Encaissements, modes et rapprochements.',
                'long_description' => 'Suivez tous les paiements (espèces, carte, virement) et rapprochez-les de vos factures et tickets.',
                'version' => '1.8.5',
                'category' => 'Vente',
                'icon' => 'payments',
                'color' => '#f59e0b',
                'permission' => 'payments.view',
                'route' => 'reports.payments',
                'route_is' => 'reports.payments',
                'nav_group' => 'Finance',
                'nav_label' => 'Paiements',
                'rating' => 4.7,
                'installs' => 12100,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Multi-modes de paiement', 'Rapprochements', 'Reporting caisse'],
                'related' => ['invoices', 'pos', 'reports'],
            ]),
            'reports' => self::def([
                'name' => 'Rapports',
                'description' => 'Analyses ventes, stock et finance.',
                'long_description' => 'Des rapports clairs pour décider : performance ventes, rotation stock, marge et tendances.',
                'version' => '2.1.0',
                'category' => 'Gestion',
                'icon' => 'reports',
                'color' => '#7c3aed',
                'permission' => 'reports.view',
                'route' => 'reports.dashboard',
                'route_is' => 'reports.*',
                'nav_group' => 'Pilotage',
                'nav_label' => 'Rapports',
                'rating' => 4.7,
                'installs' => 10240,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Rapports ventes', 'Analyse stock', 'Exports'],
                'related' => ['dashboard', 'sales', 'stock'],
            ]),
            'documents' => self::def([
                'name' => 'Documents',
                'description' => 'GED, dossiers et pièces jointes.',
                'long_description' => 'Rangez contrats, factures scannées et pièces jointes dans une GED simple, liée à vos fiches métier.',
                'version' => '1.4.0',
                'category' => 'Gestion',
                'icon' => 'documents',
                'color' => '#6366f1',
                'permission' => 'documents.view',
                'route' => 'documents.dashboard',
                'route_is' => 'documents.*',
                'nav_group' => 'Pilotage',
                'nav_label' => 'Documents',
                'rating' => 4.5,
                'installs' => 7650,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Dossiers', 'Favoris', 'Recherche'],
                'related' => ['customers', 'suppliers', 'invoices'],
            ]),
            'notifications' => self::def([
                'name' => 'Notifications',
                'description' => 'Centre d’alertes et préférences.',
                'long_description' => 'Recevez les alertes métier importantes (stock, inscriptions, paiements) et configurez vos préférences.',
                'version' => '1.3.0',
                'category' => 'Intégrations',
                'icon' => 'notifications',
                'color' => '#0ea5e9',
                'permission' => 'notifications.view',
                'route' => 'notifications.dashboard',
                'route_is' => 'notifications.*',
                'nav_group' => 'Relation Client',
                'nav_label' => 'Notifications',
                'rating' => 4.4,
                'installs' => 14200,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Centre de notifications', 'Préférences', 'Alertes critiques'],
                'related' => ['email', 'sms', 'dashboard'],
            ]),
            'users' => self::def([
                'name' => 'Utilisateurs',
                'description' => 'Comptes collaborateurs et accès boutique.',
                'long_description' => 'Invitez votre équipe, gérez les accès par boutique et suivez l’activité des utilisateurs.',
                'version' => '2.0.2',
                'category' => 'Administration',
                'icon' => 'users',
                'color' => '#64748b',
                'permission' => 'users.view',
                'route' => 'users.dashboard',
                'route_is' => 'users.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Utilisateurs',
                'rating' => 4.8,
                'installs' => 16900,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Invitations', 'Accès multi-boutiques', 'Journal de connexion'],
                'related' => ['roles', 'audit', 'settings'],
            ]),
            'roles' => self::def([
                'name' => 'Permissions',
                'description' => 'Rôles et matrices de droits RBAC.',
                'long_description' => 'Définissez précisément qui peut voir, créer ou valider chaque action métier grâce à une matrice de permissions claire.',
                'version' => '1.9.0',
                'category' => 'Administration',
                'icon' => 'roles',
                'color' => '#475569',
                'permission' => 'roles.view',
                'route' => 'roles.dashboard',
                'route_is' => 'roles.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Rôles & Permissions',
                'rating' => 4.7,
                'installs' => 9800,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Rôles personnalisés', 'Matrice de droits', 'Historique des changements'],
                'related' => ['users', 'audit'],
            ]),
            'settings' => self::def([
                'name' => 'Paramètres',
                'description' => 'Configuration entreprise et boutique.',
                'long_description' => 'Paramétrez la devise, la fiscalité, les options de caisse et les préférences globales de votre workspace.',
                'version' => '2.2.0',
                'category' => 'Administration',
                'icon' => 'settings',
                'color' => '#334155',
                'permission' => 'settings.view',
                'route' => 'settings.index',
                'route_is' => 'settings.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Paramètres',
                'rating' => 4.6,
                'installs' => 18000,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Paramètres entreprise', 'Options boutique', 'Préférences'],
                'related' => ['branding', 'system', 'modules'],
            ]),
            'branding' => self::def([
                'name' => 'Branding',
                'description' => 'Identité visuelle et personnalisation.',
                'long_description' => 'Appliquez votre identité : logo, couleurs et apparence pour une expérience GreenPOS à votre image.',
                'version' => '1.2.0',
                'category' => 'Administration',
                'icon' => 'branding',
                'color' => '#14b8a6',
                'permission' => 'settings.view',
                'route' => 'branding.index',
                'route_is' => 'branding.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Branding',
                'rating' => 4.5,
                'installs' => 6400,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['nouveau'],
                'features' => ['Logo', 'Couleurs', 'Aperçu live'],
                'related' => ['settings', 'documents'],
            ]),
            'system' => self::def([
                'name' => 'Sauvegardes & Santé',
                'description' => 'Sauvegardes, restauration et surveillance.',
                'long_description' => 'Surveillez la santé de votre instance et gérez les sauvegardes pour sécuriser vos données métier.',
                'version' => '1.1.0',
                'category' => 'Administration',
                'icon' => 'system',
                'color' => '#0f766e',
                'permission' => 'settings.view',
                'route' => 'system.dashboard',
                'route_is' => 'system.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Sauvegardes & Santé',
                'rating' => 4.4,
                'installs' => 5200,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Sauvegardes', 'Indicateurs santé', 'Restauration'],
                'related' => ['settings', 'audit'],
            ]),
            'multi_store' => self::def([
                'name' => 'Multi-boutiques',
                'description' => 'Gestion multi-magasins et bascule rapide.',
                'long_description' => 'Pilotez plusieurs points de vente dans un même workspace : stocks séparés, bascule instantanée et reporting consolidé.',
                'version' => '2.0.0',
                'category' => 'Administration',
                'icon' => 'stores',
                'color' => '#0d9488',
                'permission' => 'stores.view',
                'route' => 'stores.dashboard',
                'route_is' => 'stores.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Boutiques',
                'rating' => 4.8,
                'installs' => 8120,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Boutiques illimitées*', 'Bascule workspace', 'Stocks séparés'],
                'related' => ['stock', 'pos', 'users'],
            ]),
            'crm' => self::def([
                'name' => 'CRM',
                'description' => 'Leads, pipeline commercial et activités.',
                'long_description' => 'Transformez vos prospects en clients : pipeline, opportunités, activités et suivi commercial unifié.',
                'version' => '1.5.0',
                'category' => 'Gestion',
                'icon' => 'crm',
                'color' => '#2563eb',
                'permission' => null,
                'route' => 'crm.dashboard',
                'route_is' => 'crm.*',
                'nav_group' => 'Relation Client',
                'nav_label' => 'CRM Enterprise',
                'rating' => 4.6,
                'installs' => 5430,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => ['Pipeline', 'Opportunités', 'Activités', 'Objectifs'],
                'related' => ['customers', 'quotes', 'ai'],
            ]),
            'hr' => self::def([
                'name' => 'RH',
                'description' => 'Gestion des collaborateurs et plannings.',
                'long_description' => 'Module RH léger pour centraliser les collaborateurs, plannings et informations internes (roadmap).',
                'version' => '0.2.0',
                'category' => 'Gestion',
                'icon' => 'users',
                'color' => '#4f46e5',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.2,
                'installs' => 890,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => ['Fiches collaborateurs', 'Plannings', 'Documents RH'],
                'related' => ['users', 'documents'],
            ]),
            'accounting' => self::def([
                'name' => 'Comptabilité',
                'description' => 'Exports comptables et journaux.',
                'long_description' => 'Préparez vos exports comptables et journaux pour votre expert-comptable. Module en cours d’enrichissement.',
                'version' => '0.4.0',
                'category' => 'Finance',
                'icon' => 'accounting',
                'color' => '#b45309',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.3,
                'installs' => 2100,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'features' => ['Exports', 'Journaux', 'Rapprochements'],
                'related' => ['invoices', 'payments', 'reports'],
            ]),
            'ai' => self::def([
                'name' => 'GreenPOS AI',
                'description' => 'Assistant IA contextuel pour votre ERP.',
                'long_description' => 'Interrogez vos données, obtenez des suggestions et accélerez vos tâches quotidiennes grâce à GreenPOS AI, conçu pour le retail et la distribution.',
                'version' => '1.2.0',
                'category' => 'Intelligence',
                'icon' => 'ai',
                'color' => '#8b5cf6',
                'permission' => null,
                'route' => 'ai.dashboard',
                'route_is' => 'ai.*',
                'nav_group' => 'Pilotage',
                'nav_label' => 'GreenPOS AI',
                'rating' => 4.9,
                'installs' => 4280,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => [
                    'Assistant conversationnel',
                    'Suggestions métier',
                    'Multi-fournisseurs LLM',
                    'Journal des actions IA',
                ],
                'related' => ['dashboard', 'crm', 'reports'],
            ]),
            'api' => self::def([
                'name' => 'API',
                'description' => 'Accès API REST et webhooks.',
                'long_description' => 'Connectez GreenPOS à votre écosystème via une API sécurisée et des webhooks événementiels.',
                'version' => '0.8.0',
                'category' => 'Intégrations',
                'icon' => 'api',
                'color' => '#0f172a',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.5,
                'installs' => 1560,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'features' => ['API REST', 'Clés d’accès', 'Webhooks'],
                'related' => ['ecommerce', 'whatsapp', 'email'],
            ]),
            'whatsapp' => self::def([
                'name' => 'WhatsApp',
                'description' => 'Notifications et messages WhatsApp Business.',
                'long_description' => 'Envoyez confirmations, rappels et tickets via WhatsApp Business (roadmap).',
                'version' => '0.1.0',
                'category' => 'Intégrations',
                'icon' => 'api',
                'color' => '#16a34a',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.4,
                'installs' => 980,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => ['Messages transactionnels', 'Modèles', 'Statuts de livraison'],
                'related' => ['sms', 'email', 'notifications'],
            ]),
            'sms' => self::def([
                'name' => 'SMS',
                'description' => 'Campagnes et alertes SMS.',
                'long_description' => 'Diffusez des alertes et campagnes SMS à vos clients (roadmap).',
                'version' => '0.1.0',
                'category' => 'Intégrations',
                'icon' => 'notifications',
                'color' => '#0284c7',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.2,
                'installs' => 740,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Alertes SMS', 'Campagnes', 'Crédits'],
                'related' => ['whatsapp', 'email', 'customers'],
            ]),
            'email' => self::def([
                'name' => 'Email',
                'description' => 'Envoi d’emails transactionnels et templates.',
                'long_description' => 'Automatisez l’envoi de devis, factures et notifications par email avec des templates professionnels.',
                'version' => '0.5.0',
                'category' => 'Intégrations',
                'icon' => 'notifications',
                'color' => '#ea580c',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.5,
                'installs' => 3200,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'features' => ['Templates', 'Envois transactionnels', 'Suivi'],
                'related' => ['invoices', 'quotes', 'notifications'],
            ]),
            'ecommerce' => self::def([
                'name' => 'E-commerce',
                'description' => 'Connexion boutique en ligne et sync catalogue.',
                'long_description' => 'Synchronisez catalogue, stocks et commandes avec votre boutique en ligne (roadmap).',
                'version' => '0.2.0',
                'category' => 'Intégrations',
                'icon' => 'api',
                'color' => '#db2777',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.3,
                'installs' => 1180,
                'compatibility' => ['Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => ['Sync catalogue', 'Commandes web', 'Stocks temps réel'],
                'related' => ['products', 'stock', 'api'],
            ]),
            'mobile' => self::def([
                'name' => 'Application Mobile',
                'description' => 'Companion mobile pour managers et équipes.',
                'long_description' => 'Suivez vos KPIs, validez des inventaires et consultez les ventes depuis votre smartphone (roadmap).',
                'version' => '0.3.0',
                'category' => 'Mobile',
                'icon' => 'mobile',
                'color' => '#111827',
                'coming_soon' => true,
                'nav_group' => null,
                'rating' => 4.4,
                'installs' => 2650,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'badges' => ['nouveau'],
                'features' => ['KPIs mobiles', 'Notifications push', 'Inventaire terrain'],
                'related' => ['dashboard', 'inventory', 'pos'],
            ]),
            'audit' => self::def([
                'name' => 'Journal',
                'description' => 'Journal d’audit des actions sensibles.',
                'long_description' => 'Traçabilité complète des actions utilisateurs pour la conformité et le contrôle interne.',
                'version' => '1.3.0',
                'category' => 'Administration',
                'icon' => 'audit',
                'color' => '#57534e',
                'permission' => 'audit.view',
                'route' => 'audit.dashboard',
                'route_is' => 'audit.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Journal d\'audit',
                'rating' => 4.6,
                'installs' => 6900,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Événements détaillés', 'Filtres', 'Export'],
                'related' => ['users', 'roles', 'system'],
            ]),
            'companies' => self::def([
                'name' => 'Entreprises',
                'description' => 'Multi-entreprises et workspaces.',
                'long_description' => 'Gérez plusieurs entreprises depuis un même compte et basculez de workspace en toute sécurité.',
                'version' => '1.4.0',
                'category' => 'Administration',
                'icon' => 'companies',
                'color' => '#134e4a',
                'permission' => 'companies.view',
                'route' => 'companies.dashboard',
                'route_is' => 'companies.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Entreprises',
                'rating' => 4.5,
                'installs' => 4100,
                'compatibility' => ['Business', 'Enterprise'],
                'premium' => true,
                'features' => ['Multi-entreprises', 'Bascule workspace', 'Isolation des données'],
                'related' => ['multi_store', 'users', 'settings'],
            ]),
            'modules' => self::def([
                'name' => 'Catalogue des Modules',
                'description' => 'GreenPOS Module Store — activez vos applications.',
                'long_description' => 'Parcourez le Module Store GreenPOS et construisez votre ERP en installant uniquement les applications dont vous avez besoin.',
                'version' => '2.0.0',
                'category' => 'Administration',
                'icon' => 'modules',
                'color' => '#0f766e',
                'permission' => 'settings.view',
                'route' => 'modules.index',
                'route_is' => 'modules.*',
                'nav_group' => 'Administration',
                'nav_label' => 'Catalogue des Modules',
                'rating' => 5.0,
                'installs' => 18420,
                'compatibility' => ['Starter', 'Business', 'Enterprise'],
                'badges' => ['updated'],
                'features' => ['Découverte App Store', 'Activation en un clic', 'Détail de chaque module'],
                'related' => ['settings', 'dashboard'],
            ]),
        ];
    }

    /**
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     */
    protected static function def(array $data): array
    {
        return array_merge([
            'developer' => 'GreenPOS',
            'compatibility' => ['Starter', 'Business', 'Enterprise'],
            'rating' => 4.5,
            'installs' => 1000,
            'premium' => false,
            'badges' => [],
            'long_description' => $data['description'] ?? '',
            'features' => [],
            'changelog' => [
                ['version' => $data['version'] ?? '1.0.0', 'date' => '2026-06-01', 'notes' => 'Publication initiale du module.'],
            ],
            'prerequisites' => [],
            'related' => [],
            'screenshots' => 3,
            'coming_soon' => false,
            'permission' => null,
            'route' => null,
            'route_is' => null,
            'nav_group' => null,
            'nav_label' => null,
            'color' => '#0d9488',
        ], $data);
    }

    /** @return array<string, string> */
    public static function labels(): array
    {
        return collect(self::all())->mapWithKeys(fn ($m, $k) => [$k => $m['name']])->all();
    }

    /** @return list<string> */
    public static function keys(): array
    {
        return array_keys(self::all());
    }

    public static function get(string $key): ?array
    {
        $meta = self::all()[$key] ?? null;
        if (! $meta) {
            return null;
        }

        return array_merge($meta, ['key' => $key]);
    }

    /** @return list<string> */
    public static function defaultModulesForPlan(string $code): array
    {
        $all = self::keys();

        return match ($code) {
            'starter' => [
                'dashboard', 'products', 'categories', 'brands', 'stock', 'customers', 'pos',
                'sales', 'invoices', 'users', 'settings', 'branding', 'system', 'modules', 'notifications',
            ],
            'standard', 'business' => [
                'dashboard', 'products', 'categories', 'brands', 'stock', 'inventory',
                'purchases', 'suppliers', 'customers', 'pos', 'sales', 'quotes', 'invoices',
                'payments', 'reports', 'documents', 'notifications', 'users', 'settings',
                'branding', 'system', 'multi_store', 'modules', 'companies', 'email',
            ],
            'professional' => array_values(array_diff($all, ['accounting', 'mobile', 'hr'])),
            'enterprise' => $all,
            default => [
                'dashboard', 'products', 'stock', 'customers', 'pos', 'users', 'settings', 'branding', 'system', 'modules',
            ],
        };
    }

    public static function moduleForAbility(string $ability): ?string
    {
        $prefix = explode('.', $ability)[0] ?? null;

        $map = [
            'products' => 'products',
            'stock' => 'stock',
            'purchases' => 'purchases',
            'suppliers' => 'suppliers',
            'customers' => 'customers',
            'pos' => 'pos',
            'sales' => 'sales',
            'quotes' => 'quotes',
            'invoices' => 'invoices',
            'payments' => 'payments',
            'reports' => 'reports',
            'documents' => 'documents',
            'notifications' => 'notifications',
            'users' => 'users',
            'roles' => 'roles',
            'settings' => 'settings',
            'branding' => 'branding',
            'system' => 'system',
            'stores' => 'multi_store',
            'companies' => 'companies',
            'audit' => 'audit',
            'crm' => 'crm',
            'ai' => 'ai',
            'modules' => 'modules',
        ];

        return $map[$prefix] ?? null;
    }

    /** @return list<string> */
    public static function categories(): array
    {
        return array_values(array_filter(self::STORE_FILTERS, fn ($c) => $c !== 'Tous'));
    }

    /** @return list<string> */
    public static function storeFilters(): array
    {
        return self::STORE_FILTERS;
    }

    /** @return array<string, string> */
    public static function iconPaths(): array
    {
        return [
            'dashboard' => 'M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z',
            'ai' => 'M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3z',
            'reports' => 'M9 17v-6m4 6V7m4 10v-3M5 21h14a2 2 0 002-2V5',
            'documents' => 'M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z',
            'pos' => 'M3 3h8v8H3V3zm10 0h8v8h-8V3zM3 13h8v8H3v-8zm10 0h8v8h-8v-8z',
            'sales' => 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2',
            'products' => 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4',
            'categories' => 'M4 6h16M4 12h16M4 18h10',
            'brands' => 'M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A2 2 0 013 12V7a4 4 0 014-4z',
            'stock' => 'M4 7h16M4 12h16M4 17h10',
            'inventory' => 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2',
            'purchases' => 'M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2 9m12-9l2 9',
            'suppliers' => 'M17 20h5v-2a4 4 0 00-4-4h-1M9 20H4v-2a4 4 0 014-4h1m4-4a4 4 0 11-8 0 4 4 0 018 0z',
            'customers' => 'M17 20h5v-2a4 4 0 00-4-4h-1M9 20H4v-2a4 4 0 014-4h1m4-4a4 4 0 11-8 0 4 4 0 018 0z',
            'crm' => 'M3 7h18M3 12h12M3 17h18',
            'notifications' => 'M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6 6 0 10-12 0v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9',
            'payments' => 'M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2z',
            'invoices' => 'M9 12h6m-6 4h6M7 4h10a2 2 0 012 2v14l-4-2-4 2-4-2-4 2V6a2 2 0 012-2z',
            'quotes' => 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2',
            'accounting' => 'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z',
            'companies' => 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5',
            'stores' => 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5',
            'users' => 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1z',
            'roles' => 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944',
            'audit' => 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2',
            'settings' => 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z',
            'system' => 'M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4',
            'modules' => 'M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zm10 0a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zm10 0a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z',
            'branding' => 'M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343',
            'api' => 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4',
            'mobile' => 'M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z',
        ];
    }
}
