<?php

namespace App\Support;

class SettingsDefaults
{
    public static function for(string $group): array
    {
        return match ($group) {
            'tax' => [
                'default_tax_rate' => 20,
                'prices_include_tax' => false,
                'tax_label' => 'TVA',
                'tax_number_label' => 'ICE',
                'show_tax_on_tickets' => true,
                'tax_rates' => [
                    ['name' => 'TVA 20%', 'rate' => 20],
                    ['name' => 'TVA 14%', 'rate' => 14],
                    ['name' => 'TVA 10%', 'rate' => 10],
                    ['name' => 'TVA 7%', 'rate' => 7],
                    ['name' => 'Exonéré', 'rate' => 0],
                ],
            ],
            'currencies' => [
                'default_currency' => 'MAD',
                'available' => ['MAD', 'EUR', 'USD'],
                'decimal_places' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'rounding_mode' => 'standard',
            ],
            'languages' => [
                'default_locale' => 'fr',
                'available' => ['fr', 'ar', 'en'],
                'fallback_locale' => 'fr',
            ],
            'numbering' => [
                'invoice_prefix' => 'FAC',
                'invoice_padding' => 4,
                'quote_prefix' => 'DEV',
                'quote_padding' => 4,
                'sale_prefix' => 'VTE',
                'sale_padding' => 4,
                'pos_prefix' => 'TKT',
                'pos_padding' => 4,
                'credit_note_prefix' => 'AVR',
                'purchase_prefix' => 'CMD',
                'reset_yearly' => true,
                'include_year' => true,
            ],
            'pos' => [
                'auto_open_session' => false,
                'auto_close_session' => false,
                'print_ticket' => true,
                'print_copies' => 1,
                'default_printer' => '',
                'barcode_reader' => true,
                'scanner_enabled' => true,
                'default_cash_drawer' => '',
                'allow_held_tickets' => true,
                'require_customer' => false,
                'show_stock_warning' => true,
                'receipt_footer' => 'Merci de votre visite',
            ],
            'invoicing' => [
                'default_payment_terms' => '30 jours',
                'default_due_days' => 30,
                'pdf_template' => 'standard',
                'show_logo' => true,
                'footer_notes' => '',
                'legal_mentions' => '',
                'auto_send_email' => false,
                'numbering_aligned' => true,
            ],
            'payments' => [
                'default_currency' => 'MAD',
                'allow_partial' => true,
                'allow_refunds' => true,
                'rounding_enabled' => true,
                'rounding_step' => 0.05,
                'methods' => [
                    'cash' => true,
                    'card' => true,
                    'bank_transfer' => true,
                    'mobile' => true,
                    'check' => true,
                    'other' => true,
                ],
            ],
            'notifications' => [
                'email_enabled' => true,
                'sms_enabled' => false,
                'sms_prepared' => true,
                'internal_enabled' => true,
                'stock_alerts' => true,
                'stock_alert_threshold' => true,
                'cash_alerts' => true,
                'invoice_overdue' => true,
                'low_stock_email' => true,
                'daily_summary' => false,
            ],
            'security' => [
                'session_lifetime' => 120,
                'password_min_length' => 8,
                'password_require_mixed' => true,
                'password_require_numbers' => true,
                'password_require_symbols' => false,
                'two_factor_prepared' => true,
                'two_factor_enabled' => false,
                'audit_logging' => true,
                'allowed_devices_only' => false,
                'max_login_attempts' => 5,
            ],
            'backup' => [
                'auto_backup' => false,
                'frequency' => 'daily',
                'retention_days' => 30,
                'include_files' => true,
                'last_backup_at' => null,
                'note' => '',
            ],
            'appearance' => [
                'theme' => 'system',
                'primary_color' => '#0f766e',
                'sidebar_style' => 'dark',
                'date_format' => 'd/m/Y',
                'time_format' => 'H:i',
                'amount_format' => 'fr',
                'favicon_path' => null,
                'compact_mode' => false,
            ],
            'branding' => [
                'trade_name' => '',
                'tagline' => '',
                'logo_path' => null,
                'logo_compact_path' => null,
                'favicon_path' => null,
                'primary_color' => '#0f766e',
                'secondary_color' => '#134e4a',
                'button_color' => '#0f766e',
                'link_color' => '#0d9488',
                'theme' => 'auto',
                'density' => 'comfortable',
                'login_background_path' => null,
                'login_logo_path' => null,
                'login_welcome' => 'Bienvenue sur votre espace GreenPOS',
                'login_footer' => '© GreenPOS — Tous droits réservés',
                'invoice_logo_path' => null,
                'invoice_primary_color' => '#0f766e',
                'invoice_header' => '',
                'invoice_footer' => '',
                'invoice_signature_path' => null,
                'invoice_stamp_path' => null,
                'invoice_legal' => '',
                'timezone' => 'Africa/Casablanca',
                'locale' => 'fr',
                'currency' => 'MAD',
                'date_format' => 'd/m/Y',
                'number_format' => 'fr',
                'emails' => [
                    'welcome' => [
                        'subject' => 'Bienvenue sur GreenPOS',
                        'body' => "Bonjour {{name}},\n\nBienvenue sur GreenPOS. Votre espace {{company}} est prêt.\n\nCordialement,\nL’équipe {{company}}",
                    ],
                    'password_reset' => [
                        'subject' => 'Réinitialisation de votre mot de passe',
                        'body' => "Bonjour {{name}},\n\nCliquez sur le lien pour réinitialiser votre mot de passe : {{link}}\n\nSi vous n’êtes pas à l’origine de cette demande, ignorez cet e-mail.",
                    ],
                    'invoice' => [
                        'subject' => 'Votre facture {{number}}',
                        'body' => "Bonjour {{name}},\n\nVeuillez trouver ci-joint votre facture {{number}} d’un montant de {{amount}}.\n\nMerci de votre confiance.",
                    ],
                    'quote' => [
                        'subject' => 'Votre devis {{number}}',
                        'body' => "Bonjour {{name}},\n\nVoici votre devis {{number}}. N’hésitez pas à nous contacter pour toute question.",
                    ],
                    'payment' => [
                        'subject' => 'Confirmation de paiement',
                        'body' => "Bonjour {{name}},\n\nNous avons bien reçu votre paiement de {{amount}}.\n\nMerci.",
                    ],
                    'notification' => [
                        'subject' => 'Notification GreenPOS',
                        'body' => "Bonjour {{name}},\n\n{{message}}\n\n— {{company}}",
                    ],
                ],
            ],
            'integrations' => [
                'smtp_prepared' => true,
                'sms_gateway_prepared' => true,
                'payment_gateway_prepared' => true,
                'webhook_url' => '',
                'api_enabled' => false,
                'notes' => 'Les connecteurs externes seront activés dans une prochaine version.',
            ],
            default => [],
        };
    }
}
